name: cardin
version: 0.0.0-dev.1

description: Flutter Cardin theme

homepage: https://github.com/chunghha/cardin.dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  supercharged: ^1.12.0

flutter:
  fonts:
    - family: Nunito
      fonts:
        - asset: packages/cardin/fonts/Nunito-Light.ttf
          weight: 300
        - asset: packages/cardin/fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: packages/cardin/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: packages/cardin/fonts/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: packages/cardin/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: packages/cardin/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: packages/cardin/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: packages/cardin/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Noto Sans CJK
      fonts:
        - asset: packages/cardin/fonts/NotoSansCJK-Regular.ttc
          weight: 300
        - asset: packages/cardin/fonts/NotoSansCJK-Bold.ttc
          weight: 700
    - family: Tibetan Machine Uni
      fonts:
        - asset: packages/cardin/fonts/TibetanMachineUni.ttf
          weight: 300
    - family: Liberation Serif
      fonts:
        - asset: packages/cardin/fonts/LiberationSerif-Regular.ttf
          weight: 300
        - asset: packages/cardin/fonts/LiberationSerif-Italic.ttf
          weight: 300
          style: italic
        - asset: packages/cardin/fonts/LiberationSerif-Bold.ttf
          weight: 700
        - asset: packages/cardin/fonts/LiberationSerif-BoldItalic.ttf
          weight: 700
          style: italic